### ISSUE TITLE
No response from server

### ISSUE THREAD

**Issue by arielchai** [drlight17/talk-electron#1]
Hey thanks for the app!

Launched it (win release, on win10), and I get notifications fine.

But shortly after when opening the conversation, the app gets stuck on "waiting for response from server".
Restarting app works, but this issue reoccurs very fast after going into a conversation.

![NcTalkElectro_issue_stuck](https://github.com/user-attachments/assets/04c7ac04-19e9-4e2a-a135-a2b2ae36e6da)

**Comment by drlight17** [comment]
Hello! Thanks for feedback. Could you please show console output in devtools (F12) when this issue occurs?

**Comment by arielchai** [comment]
Sure thing, might take me a while but will do, thank you!

**Comment by drlight17** [comment]
> Sure thing, might take me a while but will do, thank you!

Also check new version - I've increased check alive interval from 5s to 10s. Maybe it will help.

**Comment by drlight17** [comment]
One more thing: check your Nextcloud instance web server for "busy" errors or warnings. For example, in case of using php-fpm check it's log for something like this:
`
WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 8 children, there are 0 idle, and 31 total children
`
If so you could increse pm parametres in ./pool.d/www.conf to something like this:
```
pm.max_children = 900
pm.start_servers = 95
pm.min_spare_servers = 50
pm.max_spare_servers = 150
pm.max_requests = 600
```
Hope this helps.

**Comment by arielchai** [comment]
Absolutely brilliant!

First of all I've updated to latest version (0.2.9), the timeouts still happened but it actually recovered after a few seconds.

Then I followed your instructions above. Chat became super responsive, and best part I have yet to see the timeouts appear (*knock on wood*)

Thank you so much for this lovely app, and detailed instructions for fix, you sir are an absolute legend! 👍

**Comment by drlight17** [comment]
I'm glad it helped. In newer version I will add configurable check alive interval.
